#!/usr/bin/env python3
"""
TELEGRAM LOG EXPORTER
=====================
Exports Clawdbot/Jarvis conversation history to readable logs

Run: python3 export_telegram_logs.py

Output: /root/jarvis-workspace/logs/telegram/
"""

import os
import json
import subprocess
from datetime import datetime
from pathlib import Path

LOG_DIR = Path("/root/jarvis-workspace/logs/telegram")
LOG_DIR.mkdir(parents=True, exist_ok=True)

def export_session_history():
    """Export current session history using clawdbot CLI or direct file access"""
    
    today = datetime.now().strftime("%Y-%m-%d")
    output_file = LOG_DIR / f"conversation_{today}.md"
    
    # Try to read session data directly from Clawdbot files
    sessions_file = Path("/root/.clawdbot/agents/main/sessions/sessions.json")
    
    if sessions_file.exists():
        with open(sessions_file, "r") as f:
            sessions = json.load(f)
        
        # Extract conversation summary
        md_content = f"""# Telegram Conversation Log

**Date:** {today}
**Exported:** {datetime.now().isoformat()}

---

## Sessions

"""
        
        for session_key, session_data in sessions.items():
            md_content += f"""### Session: {session_key}

- **Session ID:** {session_data.get('sessionId', 'N/A')}
- **Updated:** {datetime.fromtimestamp(session_data.get('updatedAt', 0)/1000).isoformat() if session_data.get('updatedAt') else 'N/A'}

---

"""
        
        with open(output_file, "w") as f:
            f.write(md_content)
        
        print(f"✅ Exported to: {output_file}")
        return str(output_file)
    
    else:
        print("❌ Could not find sessions file")
        return None


def export_inbound_media_log():
    """Log all inbound media (messages with attachments)"""
    
    media_dir = Path("/root/.clawdbot/media/inbound")
    today = datetime.now().strftime("%Y-%m-%d")
    output_file = LOG_DIR / f"media_log_{today}.md"
    
    if not media_dir.exists():
        print("❌ Media directory not found")
        return None
    
    md_content = f"""# Inbound Media Log

**Date:** {today}
**Exported:** {datetime.now().isoformat()}

---

| Filename | Type | Size | Modified |
|----------|------|------|----------|
"""
    
    for file in sorted(media_dir.iterdir(), key=lambda x: x.stat().st_mtime, reverse=True)[:50]:
        size = file.stat().st_size
        modified = datetime.fromtimestamp(file.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
        ext = file.suffix.lower()
        
        if ext in ['.jpg', '.jpeg', '.png', '.gif']:
            file_type = "🖼️ Image"
        elif ext in ['.ogg', '.mp3', '.wav']:
            file_type = "🎤 Audio"
        elif ext in ['.md', '.txt']:
            file_type = "📄 Document"
        elif ext in ['.mp4', '.webm']:
            file_type = "🎬 Video"
        else:
            file_type = f"📎 {ext}"
        
        md_content += f"| {file.name} | {file_type} | {size:,} bytes | {modified} |\n"
    
    with open(output_file, "w") as f:
        f.write(md_content)
    
    print(f"✅ Media log: {output_file}")
    return str(output_file)


def archive_daily_summary():
    """Create a daily summary of all activity"""
    
    today = datetime.now().strftime("%Y-%m-%d")
    summary_file = LOG_DIR / f"daily_summary_{today}.md"
    
    # Get workflow stats if available
    workflow_file = Path(f"/root/jarvis-workspace/evidence/workflows/{today}.jsonl")
    workflow_count = 0
    success_count = 0
    
    if workflow_file.exists():
        with open(workflow_file, "r") as f:
            for line in f:
                try:
                    record = json.loads(line)
                    workflow_count += 1
                    if record.get("output", {}).get("success"):
                        success_count += 1
                except:
                    pass
    
    # Get git commits today
    try:
        result = subprocess.run(
            ["git", "-C", "/root/jarvis-workspace", "log", "--oneline", "--since=midnight"],
            capture_output=True, text=True, timeout=10
        )
        commits = result.stdout.strip().split("\n") if result.stdout.strip() else []
    except:
        commits = []
    
    md_content = f"""# Daily Summary - {today}

**Generated:** {datetime.now().isoformat()}

---

## 📊 Statistics

| Metric | Value |
|--------|-------|
| Workflows Executed | {workflow_count} |
| Successful | {success_count} |
| Failed | {workflow_count - success_count} |
| Success Rate | {(success_count/workflow_count*100):.1f}% |
| Git Commits | {len(commits)} |

---

## 📝 Git Commits Today

"""
    
    for commit in commits[:20]:
        md_content += f"- {commit}\n"
    
    if not commits:
        md_content += "*No commits today*\n"
    
    md_content += "\n---\n\n*Auto-generated by Telegram Log Exporter*\n"
    
    with open(summary_file, "w") as f:
        f.write(md_content)
    
    print(f"✅ Daily summary: {summary_file}")
    return str(summary_file)


if __name__ == "__main__":
    print("📋 TELEGRAM LOG EXPORTER")
    print("=" * 40)
    print()
    
    export_session_history()
    export_inbound_media_log()
    archive_daily_summary()
    
    print()
    print(f"📁 All logs saved to: {LOG_DIR}")
